FROM maven:3.6.3-openjdk-11-slim as BUILDER
ARG VERSION=0.0.1-SNAPSHOT
WORKDIR /BUILD/
copy pom.xml /BUILD/
copy src /BUILD/src

RUN mvn clean package
COPY target/video-${VERSION}.jar target/application.jar

FROM openjdk:11.0.11-jre-slim
WORKDIR /app/

COPY --from=BUILDER build/target/application.jar /app/
CMD java -jar /app/application.jar